// GENERATED by BoardCraft/export_to_dart.py — DO NOT EDIT by hand.
// Source: BoardCraft/boardcraft.json
//
// Coordinates are in the *source image space* (1332 × 1265 px). The
// painter scales them to the widget size at paint time.

import 'package:flutter/material.dart';

/// Native pixel dimensions of the coordinate space used by every list
/// in this file. Painters compute a scale = min(size.w / W, size.h / H)
/// and a centering offset to render the board.
const double kBoard5pSrcWidth  = 1332.0;
const double kBoard5pSrcHeight = 1265.0;

// ── Polygon outline of the playable area ─────────────────────────────────────────
/// Board  (surface, annotation #46)
const List<Offset> kBoard = [
  Offset(410.0, 1198.0),
  Offset(226.0, 1064.0),
  Offset(62.0, 568.0),
  Offset(132.0, 350.0),
  Offset(556.0, 42.0),
  Offset(780.0, 40.0),
  Offset(1206.0, 350.0),
  Offset(1276.0, 568.0),
  Offset(1114.0, 1066.0),
  Offset(928.0, 1198.0),
];

// ── Player bandeau triangles (colored outer ribbon) ─────────────────────────────────────────
/// Bandeau base Bleu  (polygone, annotation #22)
const List<Offset> kBandeauBaseBleu = [
  Offset(464.0, 1162.0),
  Offset(662.0, 882.0),
  Offset(876.0, 1166.0),
];

/// Bandeau base Orange  (polygone, annotation #23)
const List<Offset> kBandeauBaseOrange = [
  Offset(102.0, 610.0),
  Offset(438.0, 720.0),
  Offset(228.0, 988.0),
];

/// Bandeau base Vert  (polygone, annotation #24)
const List<Offset> kBandeauBaseVert = [
  Offset(530.0, 96.0),
  Offset(194.0, 338.0),
  Offset(530.0, 444.0),
];

/// Bandeau base Rouge  (polygone, annotation #25)
const List<Offset> kBandeauBaseRouge = [
  Offset(1138.0, 340.0),
  Offset(810.0, 440.0),
  Offset(804.0, 96.0),
];

/// Bandeau base Jaune  (polygone, annotation #26)
const List<Offset> kBandeauBaseJaune = [
  Offset(1094.0, 990.0),
  Offset(896.0, 712.0),
  Offset(1226.0, 608.0),
];

// ── Player yards (white interior of each bandeau) ─────────────────────────────────────────
/// Yard Bleu  (surface, annotation #29)
const List<Offset> kYardBleu = [
  Offset(518.0, 1140.0),
  Offset(674.0, 926.0),
  Offset(820.0, 1144.0),
];

/// Yard Orange  (surface, annotation #30)
const List<Offset> kYardOrange = [
  Offset(148.0, 650.0),
  Offset(398.0, 734.0),
  Offset(246.0, 950.0),
];

/// Yard Vert  (surface, annotation #31)
const List<Offset> kYardVert = [
  Offset(254.0, 332.0),
  Offset(502.0, 148.0),
  Offset(500.0, 412.0),
];

/// Yard Rouge  (surface, annotation #32)
const List<Offset> kYardRouge = [
  Offset(834.0, 148.0),
  Offset(1086.0, 328.0),
  Offset(836.0, 412.0),
];

/// Yard Jaune  (surface, annotation #33)
const List<Offset> kYardJaune = [
  Offset(938.0, 730.0),
  Offset(1192.0, 646.0),
  Offset(1096.0, 944.0),
];

// ── Player home corridors (5 colored cells toward the center) ─────────────────────────────────────────
/// Couloir maison Bleu  (surface, annotation #35)
const List<Offset> kCouloirMaisonBleu = [
  Offset(942.0, 1092.0),
  Offset(730.0, 796.0),
  Offset(790.0, 748.0),
  Offset(1010.0, 1048.0),
];

/// Couloir maison Orange  (surface, annotation #36)
const List<Offset> kCouloirMaisonOrange = [
  Offset(330.0, 1050.0),
  Offset(548.0, 750.0),
  Offset(608.0, 794.0),
  Offset(392.0, 1094.0),
];

/// Couloir maison Vert  (surface, annotation #37)
const List<Offset> kCouloirMaisonVert = [
  Offset(156.0, 518.0),
  Offset(180.0, 448.0),
  Offset(532.0, 560.0),
  Offset(510.0, 632.0),
];

/// Couloir maison Rouge  (surface, annotation #38)
const List<Offset> kCouloirMaisonRouge = [
  Offset(630.0, 120.0),
  Offset(706.0, 118.0),
  Offset(706.0, 488.0),
  Offset(630.0, 486.0),
];

/// Couloir maison Jaune  (surface, annotation #39)
const List<Offset> kCouloirMaisonJaune = [
  Offset(806.0, 562.0),
  Offset(1158.0, 448.0),
  Offset(1182.0, 520.0),
  Offset(830.0, 634.0),
];

// ── Central pentagons (white dice frame + colored arrival pentagon) ─────────────────────────────────────────
/// Pentagone Dé  (surface, annotation #34)
const List<Offset> kPentagoneDe = [
  Offset(670.0, 742.0),
  Offset(578.0, 676.0),
  Offset(612.0, 568.0),
  Offset(728.0, 568.0),
  Offset(762.0, 678.0),
];

/// Pentagone Home  (surface, annotation #40)
const List<Offset> kPentagoneHome = [
  Offset(558.0, 488.0),
  Offset(782.0, 486.0),
  Offset(850.0, 698.0),
  Offset(670.0, 834.0),
  Offset(488.0, 704.0),
];

// ── Player home triangles (the 5 colored slices around the dice) ─────────────────────────────────────────
/// Home Bleu  (surface, annotation #41)
const List<Offset> kHomeBleu = [
  Offset(672.0, 836.0),
  Offset(670.0, 744.0),
  Offset(764.0, 678.0),
  Offset(852.0, 698.0),
];

/// Home Orange  (surface, annotation #42)
const List<Offset> kHomeOrange = [
  Offset(672.0, 832.0),
  Offset(490.0, 704.0),
  Offset(582.0, 676.0),
  Offset(670.0, 742.0),
];

/// Home Vert  (surface, annotation #43)
const List<Offset> kHomeVert = [
  Offset(492.0, 704.0),
  Offset(558.0, 488.0),
  Offset(612.0, 570.0),
  Offset(578.0, 674.0),
];

/// Home Rouge  (surface, annotation #44)
const List<Offset> kHomeRouge = [
  Offset(558.0, 490.0),
  Offset(782.0, 488.0),
  Offset(728.0, 568.0),
  Offset(614.0, 570.0),
];

/// Home Jaune  (surface, annotation #45)
const List<Offset> kHomeJaune = [
  Offset(782.0, 488.0),
  Offset(848.0, 698.0),
  Offset(760.0, 678.0),
  Offset(728.0, 570.0),
];

// ── Ring path (polygon outline) ─────────────────────────────────────────
/// Ring depuis le départ Bleu  (polygone, annotation #11)
const List<Offset> kRingDepuisLeDepartBleu = [
  Offset(904.0, 1062.0),
  Offset(716.0, 854.0),
  Offset(620.0, 848.0),
  Offset(404.0, 1142.0),
  Offset(274.0, 1050.0),
  Offset(494.0, 758.0),
  Offset(462.0, 654.0),
  Offset(108.0, 542.0),
  Offset(154.0, 396.0),
  Offset(506.0, 512.0),
  Offset(594.0, 446.0),
  Offset(586.0, 82.0),
  Offset(734.0, 82.0),
  Offset(744.0, 444.0),
  Offset(838.0, 508.0),
  Offset(1182.0, 402.0),
  Offset(1234.0, 544.0),
  Offset(874.0, 646.0),
  Offset(852.0, 752.0),
  Offset(1068.0, 1060.0),
  Offset(944.0, 1142.0),
];

// ── Token rest positions in each yard ─────────────────────────────────────────
/// 4 tokens verts  (multipoints, annotation #1)
const List<Offset> kTokensVerts = [
  Offset(330.0, 274.0),
  Offset(418.0, 250.0),
  Offset(470.0, 178.0),
  Offset(468.0, 316.0),
];

/// 4 tokens  rouge  (multipoints, annotation #2)
const List<Offset> kTokensRouge = [
  Offset(878.0, 318.0),
  Offset(924.0, 246.0),
  Offset(878.0, 172.0),
  Offset(1008.0, 268.0),
];

/// 4 tokens Orange  (multipoints, annotation #3)
const List<Offset> kTokensOrange = [
  Offset(196.0, 664.0),
  Offset(336.0, 700.0),
  Offset(262.0, 726.0),
  Offset(246.0, 822.0),
];

/// 4 tokens Bleu  (multipoints, annotation #4)
const List<Offset> kTokensBleu = [
  Offset(584.0, 1058.0),
  Offset(670.0, 1020.0),
  Offset(670.0, 952.0),
  Offset(752.0, 1056.0),
];

/// 4 tokens Jaune  (multipoints, annotation #5)
const List<Offset> kTokensJaune = [
  Offset(1000.0, 702.0),
  Offset(1140.0, 660.0),
  Offset(1084.0, 728.0),
  Offset(1090.0, 814.0),
];

// ── Single landmark points (start cells, home column entries, etc.) ─────────────────────────────────────────
/// Case départ Bleu  (annotation #6)
const Offset kCaseDepartBleu = Offset(890.0, 1086.0);

/// Case départ Orange  (annotation #7)
const Offset kCaseDepartOrange = Offset(316.0, 994.0);

/// Case départ Vert  (annotation #8)
const Offset kCaseDepartVert = Offset(226.0, 416.0);

/// Case départ Rouge  (annotation #9)
const Offset kCaseDepartRouge = Offset(742.0, 156.0);

/// Case départ Jaune  (annotation #10)
const Offset kCaseDepartJaune = Offset(1158.0, 556.0);

/// Entrée couloir maison Bleu  (annotation #12)
const Offset kEntreeCouloirMaisonBleu = Offset(958.0, 1042.0);

/// Entrée couloir maison Orange  (annotation #13)
const Offset kEntreeCouloirMaisonOrange = Offset(376.0, 1040.0);

/// Entrée couloir maison Vert  (annotation #14)
const Offset kEntreeCouloirMaisonVert = Offset(202.0, 494.0);

/// Entrée couloir maison Rouge  (annotation #15)
const Offset kEntreeCouloirMaisonRouge = Offset(666.0, 152.0);

/// Entrée couloir maison Jaune  (annotation #16)
const Offset kEntreeCouloirMaisonJaune = Offset(1136.0, 498.0);

/// Maison Bleu  (annotation #17)
const Offset kMaisonBleu = Offset(738.0, 738.0);

/// Maison Orange  (annotation #18)
const Offset kMaisonOrange = Offset(594.0, 740.0);

/// Maison Vert  (annotation #19)
const Offset kMaisonVert = Offset(562.0, 604.0);

/// Maison Rouge  (annotation #20)
const Offset kMaisonRouge = Offset(668.0, 528.0);

/// Maison Jaune  (annotation #21)
const Offset kMaisonJaune = Offset(782.0, 612.0);

/// Dé  (annotation #28)
const Offset kDe = Offset(664.0, 634.0);

// ── Multipoint sets (safe stars, etc.) ─────────────────────────────────────────
/// Cases Etoile  (multipoints, annotation #27)
const List<Offset> kCasesEtoile = [
  Offset(490.0, 1034.0),
  Offset(248.0, 588.0),
  Offset(596.0, 230.0),
  Offset(1044.0, 444.0),
  Offset(980.0, 942.0),
];
