"""Convert boardcraft.json into a Dart constants file consumed by the
Flutter painter for the 5-player board (`lib/game/board5p_geometry.dart`).

Run this anytime `boardcraft.json` is updated.
"""
import os
import json
import re

HERE = os.path.dirname(os.path.abspath(__file__))
JSON = os.path.join(HERE, "boardcraft.json")
OUT  = os.path.join(HERE, "..", "lib", "game", "board5p_geometry.dart")

# Source image dimensions — all coords below are in this space.
SRC_W, SRC_H = 1332, 1265

with open(JSON, "r", encoding="utf-8") as f:
    data = json.load(f)
annots = data["annotations"]

def slug(s: str) -> str:
    """Turn a label like '4 tokens  rouge' into 'tokens_rouge'.

    Strips accents first so "Case départ" → "case_depart", not "case_d_part".
    """
    # Strip French accents to ASCII so identifiers stay readable.
    accents = {
        "é": "e", "è": "e", "ê": "e", "ë": "e",
        "à": "a", "â": "a", "ä": "a",
        "î": "i", "ï": "i",
        "ô": "o", "ö": "o",
        "ù": "u", "û": "u", "ü": "u",
        "ç": "c",
        "É": "E", "È": "E", "Ê": "E", "Ë": "E",
        "À": "A", "Â": "A", "Ä": "A",
        "Î": "I", "Ï": "I",
        "Ô": "O", "Ö": "O",
        "Ù": "U", "Û": "U", "Ü": "U",
        "Ç": "C",
    }
    for a, b in accents.items():
        s = s.replace(a, b)
    s = re.sub(r"[^A-Za-z0-9]+", "_", s).strip("_").lower()
    # Trim leading "4_" or similar count prefixes for nicer names.
    return re.sub(r"^\d+_", "", s)

lines = []
lines.append("// GENERATED by BoardCraft/export_to_dart.py — DO NOT EDIT by hand.")
lines.append("// Source: BoardCraft/boardcraft.json")
lines.append("//")
lines.append("// Coordinates are in the *source image space* (1332 × 1265 px). The")
lines.append("// painter scales them to the widget size at paint time.")
lines.append("")
lines.append("import 'package:flutter/material.dart';")
lines.append("")
lines.append("/// Native pixel dimensions of the coordinate space used by every list")
lines.append("/// in this file. Painters compute a scale = min(size.w / W, size.h / H)")
lines.append("/// and a centering offset to render the board.")
lines.append(f"const double kBoard5pSrcWidth  = {SRC_W}.0;")
lines.append(f"const double kBoard5pSrcHeight = {SRC_H}.0;")
lines.append("")

# Group by type for clarity in the generated file.
order = [
    ("Polygon outline of the playable area",
     [a for a in annots if a["label"] == "Board"]),
    ("Player bandeau triangles (colored outer ribbon)",
     [a for a in annots if a["label"].startswith("Bandeau base ")]),
    ("Player yards (white interior of each bandeau)",
     [a for a in annots if a["label"].startswith("Yard ")]),
    ("Player home corridors (5 colored cells toward the center)",
     [a for a in annots if a["label"].startswith("Couloir maison ")]),
    ("Central pentagons (white dice frame + colored arrival pentagon)",
     [a for a in annots if a["label"] in ("Pentagone Dé", "Pentagone Home")]),
    ("Player home triangles (the 5 colored slices around the dice)",
     [a for a in annots if a["label"].startswith("Home ")
        and a["label"] != "Pentagone Home"]),
    ("Ring path (polygon outline)",
     [a for a in annots if a["label"].startswith("Ring ")]),
    ("Token rest positions in each yard",
     [a for a in annots if a["label"].startswith("4 tokens")
        or a["label"].startswith("4 tokens ")]),
    ("Single landmark points (start cells, home column entries, etc.)",
     [a for a in annots if a["type"] == "point"]),
    ("Multipoint sets (safe stars, etc.)",
     [a for a in annots if a["type"] == "multipoints"
        and not a["label"].startswith("4 tokens")]),
]

emitted = set()
for header, group in order:
    if not group:
        continue
    lines.append(f"// ── {header} ─────────────────────────────────────────")
    for a in group:
        if a["id"] in emitted:
            continue
        emitted.add(a["id"])
        name = "k" + "".join(w.capitalize() for w in slug(a["label"]).split("_"))
        pts_dart = ",\n  ".join(
            f"Offset({p['x']}.0, {p['y']}.0)" for p in a["points"])
        if a["type"] == "point":
            # Single point → emit as Offset (not a list).
            x = a["points"][0]["x"]
            y = a["points"][0]["y"]
            lines.append(f"/// {a['label']}  (annotation #{a['id']})")
            lines.append(f"const Offset {name} = Offset({x}.0, {y}.0);")
        else:
            lines.append(f"/// {a['label']}  ({a['type']}, annotation #{a['id']})")
            lines.append(f"const List<Offset> {name} = [")
            lines.append(f"  {pts_dart},")
            lines.append("];")
        lines.append("")

with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines))
print(f"Wrote {OUT}  ({len(annots)} annotations)")
